# Generated by Django 3.0.14 on 2023-03-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dateTime',
        ),
    ]
